# Generated by Django 4.2.20 on 2026-01-08 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timers', '0002_timerstate_total_paused_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('5min_before', '5分前通知'), ('rehearsal_start', 'リハーサル開始通知'), ('rehearsal_end', 'リハーサル終了通知')], max_length=20, verbose_name='通知種別')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('line_user_ids', models.JSONField(default=list, verbose_name='送信先LINE User IDs')),
                ('message', models.TextField(blank=True, verbose_name='送信メッセージ')),
                ('timer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_notifications', to='timers.timer', verbose_name='タイマー')),
            ],
            options={
                'verbose_name': 'LINE通知履歴',
                'verbose_name_plural': 'LINE通知履歴',
                'ordering': ['-sent_at'],
                'unique_together': {('timer', 'notification_type')},
            },
        ),
    ]
