# Generated by Django 4.2.20 on 2026-01-06 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=50, verbose_name='バンド名')),
                ('minutes', models.IntegerField(default=15, verbose_name='予定時間（分）')),
                ('order', models.IntegerField(verbose_name='実行順序')),
                ('actual_seconds', models.IntegerField(blank=True, null=True, verbose_name='実際にかかった時間（秒）')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了時刻')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('member1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timer_member1', to='members.member', verbose_name='担当者1')),
                ('member2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timer_member2', to='members.member', verbose_name='担当者2')),
                ('member3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timer_member3', to='members.member', verbose_name='担当者3')),
            ],
            options={
                'verbose_name': 'タイマー',
                'verbose_name_plural': 'タイマー',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始時刻')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='一時停止時刻')),
                ('elapsed_seconds', models.IntegerField(default=0, verbose_name='経過時間（秒）')),
                ('is_running', models.BooleanField(default=False, verbose_name='実行中')),
                ('is_paused', models.BooleanField(default=False, verbose_name='一時停止中')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('current_timer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timers.timer', verbose_name='現在のタイマー')),
            ],
            options={
                'verbose_name': 'タイマー状態',
                'verbose_name_plural': 'タイマー状態',
            },
        ),
    ]
