# Generated by Django 4.2.20 on 2026-01-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerstate',
            name='total_paused_seconds',
            field=models.IntegerField(default=0, verbose_name='累積一時停止時間（秒）'),
        ),
    ]
