# Generated by Django 4.2.20 on 2026-01-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0002_timerstate_total_paused_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerstate',
            name='line_notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='LINE通知有効'),
        ),
    ]
